config/routes.rb
ToptalTask::Application.routes.draw do


  root "entries#index"

  resources :entries
  resources :statistics, only: :index

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :distance, :time_period, :date_time
  validates_numericality_of :distance, :time_period

  after_create :compare_speed_and_notify_user

  def week
    date = date_time.split(' ')[0]
    Date.strptime(date, '%m/%d/%Y').strftime('%W')
  end

  def speed
    distance / (time_period.to_f / 60)
  end

  private

  def compare_speed_and_notify_user
    entries_avg_speed = (Entry.all.map(&:speed).sum / Entry.count).round(2)

    if speed > entries_avg_speed
      msg = 'You are doing great. Keep it up superman. :)'
    else
      msg = 'Most of the users are faster than you. Try harder dude. :('
    end

    NexmoClient.send_message(
      from: 'Toptal',
      to: user.mobile,
      text: msg
    )
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @entry   = Entry.new
    @entries = current_user.entries.order(created_at: :desc)
  end

  def create
    begin
      CreateEntry.new(current_user, entry_params).call
      flash[:notice] = 'Entry was successfully created.'
    rescue Exception => e
      flash[:error] = e.message
    end

    redirect_to root_path
  end

  def destroy
    @entry = Entry.find(params[:id])

    if @entry.destroy!
      flash[:notice] = "Entry was destroyed."
    else
      flash[:error] = @entry.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  private

  def entry_params
    params.require(:entry).permit(:user_id, :distance, :time_period, :date_time, :created_at, :updated_at, :distance_type, :status_weather, :status_landform)
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
  def readable_time_period(entry)
    mins = entry.time_period
    return Time.at(60 * mins).utc.strftime('%M <small>Mins</small>').html_safe if mins < 60
    Time.at(60 * mins).utc.strftime('%H <small>Hour</small> %M <small>Mins</small>').html_safe
  end

  def readable_speed(entry)
    "#{sprintf('%0.2f', entry.speed)} <small>Km/H</small>".html_safe
  end
end

app/views/entries/_entry.html.erb
<tr>
  <td><%= entry.distance %> <small>Km</small></td>
  <td><%= readable_time_period(entry) %></td>


  <td><%= entry.date_time %></td>
  <td><%= readable_speed(entry) %> </td>
  <td><%= time_ago_in_words(entry.created_at) %></td>
  <td><%= time_ago_in_words(entry.updated_at) %></td>
  <td class="actions-cell">
    <%= link_to "X", entry_path(entry),
          method: :delete,
          data: {
            confirm: "Are you sure you want to permanently delete this entry?"
          },
          class: "btn btn-sm btn-danger"
    %>
  </td>
</tr>

app/views/entries/_form.html.erb
<div>
  <%= simple_form_for(@entry, :html => {:class => 'form-vertical' }) do |f| %>
    <%= f.error_notification %>

    <div class="row">
      <div class="form-inputs form-inline">
        <div class="col-xs-4 text-center">
          <%= f.input :distance, hint: "In Kilometers." %>
        </div>
        <div class="col-xs-4 text-center">
          <%= f.input :time_period, hint: "In Minutes." %>
        </div>

        <div class="col-xs-4 text-center">
          <%= f.input :date_time, input_html: { id: 'datetimepicker' } %>
        </div>
      </div>
    </div>

    <br/>
    <div class="form-actions row text-center">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/entries/index.html.erb
<br/>

<div class="well row">
  <div id="entry-form">
    <div id="insert-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

<hr>

<table class="table table-striped">
    <tr>
      <th>Distance</th>
      <th>Time period</th>
      <th>Date time</th>
      <th>Avg Speed</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
    </tr>

    <%= render @entries %>
</table>

<br>