config/routes.rb
ToptalTask::Application.routes.draw do


  root "entries#index"

  resources :entries
  resources :statistics, only: :index

  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2015
          <br/>
          Created By <%= link_to "Eqbal", "http://www.eqbalq.com" %>
          <br/>
        </small></p>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%#= link_to content_tag(:h4, 'TopTal'), root_path, class: 'navbar-brand' %>
      <%= link_to image_tag('logo.png'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
	<li><%= link_to "Sign in", new_user_session_path %></li>
	<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
	<li class="<%= 'active' if current_page?(root_path) %>">
		<%= link_to "Home", root_path %>
	</li>

	<li class="<%= 'active' if current_page?(statistics_path) %>" >
		<%= link_to "Report", statistics_path %>
	</li>

	<li class="<%= 'active' if current_page?(edit_user_registration_path) %>">
		<%= link_to "Edit your account", edit_user_registration_path %>
	</li>

	<% if current_user.admin? %>
		<li class="<%= 'active' if current_page?(admin_root_path) %>">
			<%= link_to "Admin", admin_root_path %>
		</li>
	<% end %>

	<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "ToptalTask" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>